import logging
logger = logging.getLogger('athenataf')

from athenataf.lib.functionality.test.ConfigurationTest import ConfigurationTest

class DefaultValueCheck(ConfigurationTest):
	'''
	Test class for System General->Deafault value check.
	'''
	
	def test_ath_11045_check_default_values(self):
		#test case contains bug
		system_page = self.LeftPanel.go_to_system_page()
		system_page.assert_default_values()
		
	# def test_ath_11301_VC_vlan_field_validation(self):
		# test case contains bug #27445
		# self.take_s1_snapshot()
		# system_page = self.LeftPanel.go_to_system_page()
		# system_page.edit_vc_name()
		# system_page.edit_virtual_controller_ip_values()
		# system_page.edit_virtual_controller_ip_address()
		# system_page.set_virtual_controller_ip(self.config.config_vars.ip_add)
		# system_page.save_virtual_controller_ip_address()
		# system_page.set_timezone(self.config.config_vars.pacific_time_utc_07)
		# system_page.set_prefered_band(self.config.config_vars.prefered_band_2_4ghz)
		# system_page.set_ntp_server(self.config.config_vars.ntp_server)
		# system_page.set_vc_netmask(self.config.config_vars.vc_netmask)
		# system_page.set_vc_gateway(self.config.config_vars.vc_gateway)
		# system_page.set_vc_vlan(self.config.config_vars.vc_invalid_vlan)
		# system_page.set_dyanamic_cpu_utilization(self.config.config_vars.dynamic_cpu_utilization_disable)
		# system_page._save_settings()
		# system_page.assert_vc_vlan('true')
		# system_page.set_vc_vlan(self.config.config_vars.vc_invalid_vlan1)
		# system_page._save_settings()
		# system_page.assert_vc_vlan('true')
		# system_page.set_vc_vlan(self.config.config_vars.invalid_failover_packet_lost_count)
		# system_page._save_settings()
		# system_page.assert_vc_vlan('true')
		# system_page.edit_virtual_controller_ip_values()
		# system_page.edit_virtual_controller_ip_address()
		# system_page.set_virtual_controller_ip(self.config.config_vars.valid_syslog_server)
		# system_page.assert_vc_ip()
		# system_page.close_pop_up.click()
		# self.TopPanel.go_to_allgroups()
		# self.AllGroupPage.go_to_networks()
		# system_page = self.LeftPanel.go_to_system_page()
		# system_page.set_general_dynamic_proxy('disabled')
		# system_page.set_vc_gateway(self.config.config_vars.vc_gateway)
		# system_page.set_vc_vlan(self.config.config_vars.system_auth_shared_key)
		# system_page._save_settings()	
		# self.take_s2_snapshot()
		# system_page.set_default_vc_name()
		# system_page.set_dropdown_value_default('timezone')
		# system_page.set_dropdown_value_default('preferred band')
		# system_page.set_dropdown_value_default('dynamic cpu utilization')
		# system_page._save_settings()
		# because of bug test case is parked
		# self.take_s3_snapshot()
		# self.assert_s1_s2_diff(0)
		# self.assert_s1_s3_diff()
		# self.clear()
		
	def test_ath_11304_edit_general_section(self):
		self.take_s1_snapshot()
		system_page = self.LeftPanel.go_to_system_page()
		system_page.edit_vc_name()
		system_page.edit_virtual_controller_ip_values()
		system_page.edit_virtual_controller_ip_address()
		system_page.set_virtual_controller_ip(self.config.config_vars.ip_add)
		system_page.save_virtual_controller_ip_address()
		system_page.set_timezone(self.config.config_vars.pacific_time_utc_07)
		system_page.set_prefered_band(self.config.config_vars.prefered_band_2_4ghz)
		system_page.set_ntp_server(self.config.config_vars.ntp_server)
		system_page.set_vc_netmask(self.config.config_vars.vc_netmask)
		system_page.set_vc_gateway(self.config.config_vars.vc_gateway)
		system_page.set_vc_vlan(self.config.config_vars.vc_valid_vlan)
		system_page.set_dyanamic_cpu_utilization(self.config.config_vars.dynamic_cpu_utilization_disable)
		system_page._save_settings()
		system_page.set_timezone(self.config.config_vars.timezone_mexico)
		system_page.set_ntp_server(self.config.config_vars.valid_ip1)
		system_page.set_vc_netmask(self.config.config_vars.gen_vc_netmask)
		system_page.set_vc_gateway(self.config.config_vars.valid_ip2)
		system_page.set_vc_vlan(self.config.config_vars.valid_vc_vlan1)
		#system_page.set_dyanamic_cpu_utilization(self.config.config_vars.timezone_mexico)
		system_page._save_settings()
		#system_page.set_timezone('')
		system_page.set_ntp_server('')
		system_page.set_vc_netmask('')
		system_page.set_vc_gateway('')
		system_page.set_vc_vlan('')
		system_page._save_settings()
		self.take_s2_snapshot()
		system_page.set_default_vc_name()
		system_page.edit_virtual_controller_ip_values()
		system_page.edit_virtual_controller_ip_address()
		system_page.set_virtual_controller_ip('')
		system_page.save_virtual_controller_ip_address()
		system_page.set_prefered_band(self.config.config_vars.preferred_band_value)
		self.take_s3_snapshot()
		self.assert_s1_s2_diff(0)
		self.assert_s1_s3_diff()
		self.clear()
		
	# def test_ath_11940_vc_name_validation(self):
		# self.take_s1_snapshot()
		# system_page = self.LeftPanel.go_to_system_page()
		# system_page.edit_vc_name_values()
		# system_page.edit_vc_name_icon()
		# system_page.set_vc_name(self.config.config_vars.invalid_vc_name)
		# system_page.save_vc_name()
		# due to bug test case is parked
		# system_page.assert_vc_name()
		# self.take_s2_snapshot()
		# system_page.set_default_vc_name()
		# self.take_s3_snapshot()
		# self.assert_s1_s2_diff(0)
		# self.assert_s1_s3_diff()
		# self.clear()