import logging
logger = logging.getLogger('athenataf')

from athenataf.lib.functionality.test.ConfigurationTest import ConfigurationTest

class WidsDetection(ConfigurationTest):
	'''
		Test class for WIDS Detection.
	'''

	def test_ath_684_check_default_ui_and_values(self):
		self.take_s1_snapshot()
		wids_page = self.LeftPanel.go_to_wids_page()
		wids_page.assert_detection_page_expanded()
		wids_page.assert_protection_page_collapsed()
		wids_page.assert_detection_infra_threat_detection_level_off()
		wids_page.assert_detection_clients_threat_detection_level_off()
		wids_page.assert_detection_infrastructure_default_values()
		wids_page.assert_detection_clients_default_values()
		self.take_s2_snapshot()
		self.take_s3_snapshot()
		self.assert_s1_s2_diff(None)
		self.assert_s1_s3_diff()
		self.clear()

	def test_ath_685_infrastructure_high(self):
		self.take_s1_snapshot()
		wids_page = self.LeftPanel.go_to_wids_page()
		wids_page.set_detection_infra_threat_detection_level('High')
		wids_page.assert_detection_infrastructure_tick_icon('High')
		self.take_s2_snapshot()
		wids_page.set_detection_infra_threat_detection_level('Off')
		self.take_s3_snapshot()
		self.assert_s1_s2_diff(2)
		self.assert_s1_s3_diff()
		self.clear()

	def test_ath_686_infrastructure_medium(self):
		self.take_s1_snapshot()
		wids_page = self.LeftPanel.go_to_wids_page()
		wids_page.set_detection_infra_threat_detection_level('Medium')
		wids_page.assert_detection_infrastructure_tick_icon('Medium')
		self.take_s2_snapshot()
		wids_page.set_detection_infra_threat_detection_level('Off')
		self.take_s3_snapshot()
		self.assert_s1_s2_diff(2)
		self.assert_s1_s3_diff()
		self.clear()

	def test_ath_687_infrastructure_low(self):
		self.take_s1_snapshot()
		wids_page = self.LeftPanel.go_to_wids_page()
		wids_page.set_detection_infra_threat_detection_level('Low')
		wids_page.assert_detection_infrastructure_tick_icon('Low')
		self.take_s2_snapshot()
		wids_page.set_detection_infra_threat_detection_level('Off')
		self.take_s3_snapshot()
		self.assert_s1_s2_diff(2)
		self.assert_s1_s3_diff()
		self.clear()

	def test_ath_688_infrastructure_custom(self):
		self.take_s1_snapshot()
		wids_page = self.LeftPanel.go_to_wids_page()
		wids_page.set_detection_infra_threat_detection_level('Custom')
		wids_page.assert_detection_infra_custom_level()
		self.take_s2_snapshot()
		wids_page.set_detection_infra_threat_detection_level('Off')
		self.take_s3_snapshot()
		self.assert_s1_s2_diff(2)
		self.assert_s1_s3_diff()
		self.clear()

	def test_ath_689_infrastructure_custom_changes(self):
		self.take_s1_snapshot()
		wids_page = self.LeftPanel.go_to_wids_page()
		wids_page.set_detection_infra_threat_detection_level('Custom')
		wids_page.assert_detection_infra_custom_level()
		wids_page.set_detection_infra_threat_detection_level('Custom')
		wids_page.set_detection_infra_custom_level_to_detect_apspoofing()
		self.take_s2_snapshot()
		wids_page.set_detection_infra_threat_detection_level('Off')
		self.take_s3_snapshot()
		self.assert_s1_s2_diff(2)
		self.assert_s1_s3_diff()
		self.clear()

	def test_ath_690_infrastructure_high_with_changes(self):
		self.take_s1_snapshot()
		wids_page = self.LeftPanel.go_to_wids_page()
		wids_page.set_detection_infra_threat_detection_level('High')
		wids_page.click_detection_infra_tick_icon()
		wids_page.assert_detection_infrastructure_tick_icon('Low')
		self.take_s2_snapshot()
		wids_page.set_detection_infra_threat_detection_level('Off')
		self.take_s3_snapshot()
		self.assert_s1_s2_diff(2)
		self.assert_s1_s3_diff()
		self.clear()

	def test_ath_691_infrastructure_medium_with_changes(self):
		self.take_s1_snapshot()
		wids_page = self.LeftPanel.go_to_wids_page()
		wids_page.set_detection_infra_threat_detection_level('Medium')
		wids_page.click_detection_infra_tick_icon()
		wids_page.assert_detection_infrastructure_tick_icon('Low')
		self.take_s2_snapshot()
		wids_page.set_detection_infra_threat_detection_level('Off')
		self.take_s3_snapshot()
		self.assert_s1_s2_diff(2)
		self.assert_s1_s3_diff()
		self.clear()

	def test_ath_692_infrastructure_low_with_changes(self):
		self.take_s1_snapshot()
		wids_page = self.LeftPanel.go_to_wids_page()
		wids_page.set_detection_infra_threat_detection_level('Low')
		wids_page.click_detection_infra_tick_icon()
		wids_page.assert_detection_infrastructure_tick_icon('Low')
		self.take_s2_snapshot()
		wids_page.set_detection_infra_threat_detection_level('Off')
		self.take_s3_snapshot()
		self.assert_s1_s2_diff(2)
		self.assert_s1_s3_diff()
		self.clear()

	def test_ath_693_client_high(self):
		self.take_s1_snapshot()
		wids_page = self.LeftPanel.go_to_wids_page()
		wids_page.set_detection_clients_threat_detection_level('High')
		wids_page.assert_detection_clients_tick_icon('High')
		self.take_s2_snapshot()
		wids_page.set_detection_clients_threat_detection_level('Off')
		self.take_s3_snapshot()
		self.assert_s1_s2_diff(2)
		self.assert_s1_s3_diff()
		self.clear()

	def test_ath_694_client_medium(self):
		self.take_s1_snapshot()
		wids_page = self.LeftPanel.go_to_wids_page()
		wids_page.set_detection_clients_threat_detection_level('Medium')
		wids_page.assert_detection_clients_tick_icon('Medium')
		self.take_s2_snapshot()
		wids_page.set_detection_clients_threat_detection_level('Off')
		self.take_s3_snapshot()
		self.assert_s1_s2_diff(2)
		self.assert_s1_s3_diff()
		self.clear()

	def test_ath_696_client_low(self):
		self.take_s1_snapshot()
		wids_page = self.LeftPanel.go_to_wids_page()
		wids_page.set_detection_clients_threat_detection_level('Low')
		wids_page.assert_detection_clients_tick_icon('Low')
		self.take_s2_snapshot()
		wids_page.set_detection_clients_threat_detection_level('Off')
		self.take_s3_snapshot()
		self.assert_s1_s2_diff(2)
		self.assert_s1_s3_diff()
		self.clear()

	def test_ath_695_client_custom(self):
		self.take_s1_snapshot()
		wids_page = self.LeftPanel.go_to_wids_page()
		wids_page.set_detection_clients_threat_detection_level('Custom')
		wids_page.assert_detection_clients_custom_level()
		wids_page.set_detection_clients_threat_detection_level('Custom')
		wids_page.set_detection_clients_custom_level_to_detect_omerta_attack()
		self.take_s2_snapshot()
		wids_page.set_detection_clients_threat_detection_level('Off')
		self.take_s3_snapshot()
		self.assert_s1_s2_diff(2)
		self.assert_s1_s3_diff()
		self.clear()

	def test_ath_697_client_off(self):
		self.take_s1_snapshot()
		wids_page = self.LeftPanel.go_to_wids_page()
		wids_page.set_detection_clients_threat_detection_level('Medium')
		self.take_s2_snapshot()
		wids_page.set_detection_clients_threat_detection_level('Off')
		self.take_s3_snapshot()
		self.assert_s1_s2_diff(2)
		self.assert_s1_s3_diff()
		self.clear()

	def test_ath_698_infrastructure_off(self):
		self.take_s1_snapshot()
		wids_page = self.LeftPanel.go_to_wids_page()
		wids_page.set_detection_infra_threat_detection_level('Medium')
		self.take_s2_snapshot()
		wids_page.set_detection_infra_threat_detection_level('Off')
		self.take_s3_snapshot()
		self.assert_s1_s2_diff(2)
		self.assert_s1_s3_diff()
		self.clear()

	def test_ath_6737_client_custom_with_changes(self):
		self.take_s1_snapshot()
		wids_page = self.LeftPanel.go_to_wids_page()
		wids_page.set_detection_clients_threat_detection_level_custom_with_changes('Custom')
		wids_page.assert_detection_clients_level_custom_with_changes()
		wids_page.set_detection_clients_threat_detection_level_custom_with_changes('Custom')
		wids_page.set_detection_clients_custom_level_to_detect_disconnect_sta()
		wids_page.assert_detect_disconnect_sta()
		self.take_s2_snapshot()
		wids_page.set_detection_clients_threat_detection_level('Off')
		self.take_s3_snapshot()
		self.assert_s1_s2_diff(2)
		self.assert_s1_s3_diff()
		self.clear()

	def test_ath_6738_client_high_with_changes(self):
		self.take_s1_snapshot()
		wids_page = self.LeftPanel.go_to_wids_page()
		wids_page.set_detection_clients_threat_detection_level('High')
		wids_page.click_detection_clients_tick_icon()
		wids_page.assert_detection_clients_tick_icon('High')
		self.take_s2_snapshot()
		wids_page.set_detection_clients_threat_detection_level('Off')
		self.take_s3_snapshot()
		self.assert_s1_s2_diff(2)
		self.assert_s1_s3_diff()
		self.clear()

	def test_ath_6739_client_medium_with_changes(self):
		self.take_s1_snapshot()
		wids_page = self.LeftPanel.go_to_wids_page()
		wids_page.set_detection_clients_threat_detection_level('Medium')
		wids_page.click_detection_clients_tick_icon()
		wids_page.assert_detection_clients_tick_icon('Medium')
		self.take_s2_snapshot()
		wids_page.set_detection_clients_threat_detection_level('Off')
		self.take_s3_snapshot()
		self.assert_s1_s2_diff(2)
		self.assert_s1_s3_diff()
		self.clear()

	def test_ath_6740_client_low_with_changes(self):
		self.take_s1_snapshot()
		wids_page = self.LeftPanel.go_to_wids_page()
		wids_page.set_detection_clients_threat_detection_level('Low')
		wids_page.click_detection_clients_tick_icon('Low')
		wids_page.assert_detection_clients_tick_icon('Low')
		self.take_s2_snapshot()
		wids_page.set_detection_clients_threat_detection_level('Off')
		self.take_s3_snapshot()
		self.assert_s1_s2_diff(2)
		self.assert_s1_s3_diff()
		self.clear()

	def test_ath_6749_text_check(self):
		self.take_s1_snapshot()
		wids_page = self.LeftPanel.go_to_wids_page()
		wids_page.assert_threat_detection_level_text()
		self.take_s2_snapshot()
		self.take_s3_snapshot()
		self.assert_s1_s2_diff(2)
		self.assert_s1_s3_diff()
		self.clear()

	def test_ath_6744_save_alert(self):
		self.take_s1_snapshot()
		wids_page = self.LeftPanel.go_to_wids_page()
		wids_page.select_custom_infra_threat_detection_level()
		wids_page.protection_accordion.click()
		wids_page.assert_save_alert_pop_up(visible=True)
		wids_page.client_protect_high.click()
		wids_page.infra_protect_low.click()
		wids_page.save_settings()
		self.take_s2_snapshot()
		wids_page.detection_accordion.click()
		wids_page.assert_save_alert_pop_up()
		wids_page.protection_accordion.click()
		wids_page.revert_infrastructure_default_settings()
		wids_page.revert_clients_default_settings()
		self.take_s3_snapshot()
		self.assert_s1_s2_diff(2)
		self.assert_s1_s3_diff()
		self.clear()

	def test_ath_6753_loading_WIDS_detection_page(self):
		self.take_s1_snapshot()
		wids_page = self.LeftPanel.go_to_wids_page()
		wids_page.set_detection_infra_threat_detection_level('High')
		wids_page.assert_detection_infrastructure_tick_icon('High')
		self.take_s2_snapshot()
		wids_page.set_detection_infra_threat_detection_level('Off')
		self.take_s3_snapshot()
		self.assert_s1_s2_diff(2)
		self.assert_s1_s3_diff()
		self.clear()
		
	def test_ath_6756_detection_help_text_availablility(self):
		self.take_s1_snapshot()
		wids_page = self.LeftPanel.go_to_wids_page()
		wids_page.click_help()
		wids_page.check_detection_help_text_availablility()
		self.take_s2_snapshot()
		self.assert_s1_s2_diff(None)
		wids_page.click_help()	
		self.clear()

	def test_ath_11127_detection_help_text_availablility(self):
		wids_page = self.LeftPanel.go_to_wids_page()
		wids_page.click_help()
		wids_page.check_detection_help_text_availablility()
		wids_page.click_help()	
		
	def test_ath_11124_save_alert(self):
		wids_page = self.LeftPanel.go_to_wids_page()
		wids_page.select_custom_infra_threat_detection_level()
		wids_page.protection_accordion.click()
		wids_page.click_confirm_save_cancel()
		wids_page.click_cancel_settings()
		wids_page.assert_detection_level_defaults()
		wids_page.infra_detect_low.click()
		wids_page.click_monitoring_module()

	def test_ath_11126_try_loading_wids_using_different_browsers(self):
		self.take_s1_snapshot()
		wids_page = self.LeftPanel.go_to_wids_page()
		wids_page.set_detection_infra_threat_detection_level('Low')
		wids_page.click_detection_infra_tick_icon()
		wids_page.set_detection_clients_threat_detection_level('High')
		self.take_s2_snapshot()
		wids_page.set_detection_infra_threat_detection_level('Off')
		wids_page.set_detection_clients_threat_detection_level('Off')
		self.take_s3_snapshot()
		self.assert_s1_s2_diff(2)
		self.assert_s1_s3_diff()
		self.clear()
	