import logging
logger = logging.getLogger('athenataf')

from athenataf.lib.functionality.test.ConfigurationTest import ConfigurationTest

class Routing(ConfigurationTest):
	'''
		Test class for Routing.
	'''
	
	def test_ath_8332_add_route(self):
		self.take_s1_snapshot()
		vpn_obj = self.LeftPanel.go_to_vpn()
		vpn_obj.got_to_vpn_routing()
		# vpn_obj.assert_edit_field_error()
		vpn_obj.click_new_route()
		vpn_obj.add_route()
		vpn_obj.assert_route()
		vpn_obj.buy_time()
		self.take_s2_snapshot()
		vpn_obj.delete_route()
		vpn_obj.save_settings()
		vpn_obj.buy_time()
		self.take_s3_snapshot()
		self.assert_s1_s2_diff(None)
		self.assert_s1_s3_diff()
		self.clear()
		
	def test_ath_8333_edit_route(self):
		self.take_s1_snapshot()
		vpn_obj = self.LeftPanel.go_to_vpn()
		vpn_obj.got_to_vpn_routing()
		# vpn_obj.assert_edit_field_error()
		vpn_obj.click_new_route()
		vpn_obj.add_route()
		vpn_obj.assert_route()
		vpn_obj.clicking_edit_route()
		vpn_obj.assert_edit_route_fields()
		vpn_obj.edit_route()
		vpn_obj.assert_edited_route()
		vpn_obj.buy_time()
		self.take_s2_snapshot()
		vpn_obj.delete_route()
		vpn_obj.save_settings()
		vpn_obj.buy_time()	
		self.take_s3_snapshot()
		self.assert_s1_s2_diff(None)
		self.assert_s1_s3_diff()
		self.clear()

	def test_ath_8334_delete_route(self):
		self.take_s1_snapshot()
		vpn_obj = self.LeftPanel.go_to_vpn()
		vpn_obj.got_to_vpn_routing()
		# vpn_obj.assert_edit_field_error()
		vpn_obj.click_new_route()
		vpn_obj.add_route()
		vpn_obj.assert_route()
		vpn_obj.buy_time()
		self.take_s2_snapshot()
		vpn_obj.delete_route()
		vpn_obj.save_settings()
		vpn_obj.buy_time()
		self.take_s3_snapshot()
		self.assert_s1_s2_diff(None)
		self.assert_s1_s3_diff()
		self.clear()
		
	def test_ath_11198_add_route(self):
		self.take_s1_snapshot()
		vpn_obj = self.LeftPanel.go_to_vpn()
		vpn_obj.got_to_vpn_routing()
		vpn_obj.click_new_route()
		vpn_obj._assert_edit_field_error()
		vpn_obj.add_route()
		vpn_obj.assert_route()
		vpn_obj.buy_time()
		self.take_s2_snapshot()
		vpn_obj.delete_route()
		vpn_obj.save_settings()
		vpn_obj.buy_time()
		self.take_s3_snapshot()
		self.assert_s1_s2_diff(None)
		self.assert_s1_s3_diff()
		self.clear()

	def test_ath_11199_edit_route(self):
		self.take_s1_snapshot()
		vpn_obj = self.LeftPanel.go_to_vpn()
		vpn_obj.got_to_vpn_routing()
		vpn_obj.click_new_route()
		vpn_obj.add_route()
		vpn_obj.assert_route()
		vpn_obj.clicking_edit_route()
		vpn_obj.assert_edit_route_fields()
		vpn_obj.edit_route()
		vpn_obj.assert_edited_route()
		vpn_obj.buy_time()
		self.take_s2_snapshot()
		vpn_obj.delete_route()
		vpn_obj.save_settings()
		vpn_obj.buy_time() 
		self.take_s3_snapshot()
		self.assert_s1_s2_diff(None)
		self.assert_s1_s3_diff()
		self.clear()

	def test_ath_11200_delete_route(self):
		self.take_s1_snapshot()
		vpn_obj = self.LeftPanel.go_to_vpn()
		vpn_obj.got_to_vpn_routing()
		vpn_obj.click_new_route()
		vpn_obj.add_route()
		vpn_obj.assert_route()
		vpn_obj.buy_time()
		self.take_s2_snapshot()
		vpn_obj.delete_route()
		vpn_obj.save_settings()
		vpn_obj.buy_time()
		self.take_s3_snapshot()
		self.assert_s1_s2_diff(None)
		self.assert_s1_s3_diff()
		self.clear()		