import logging
logger = logging.getLogger('athenataf')
from athenataf.lib.functionality.test.ConfigurationTest import ConfigurationTest

class VoiceSecurityLevelPersonal(ConfigurationTest):
	'''
	Test class for Voice Security Level Personal testcases.
	'''

	def test_ath_9405_create_personal_wpa_2_personal_voice_network_with_passphrase(self):
		self.NetworkPage.delete_network_if_present()
		self.take_s1_snapshot()
		basic_info = self.NetworkPage.create_new_network()
		vlan_obj = basic_info.voice_network_info()
		security = vlan_obj.use_vlan_defaults()
		access = security.assert_roaming_defaults(True,False)
		access.finish_network_setup()
		self.NetworkPage.assert_new_network()
		edit_network_page = self.NetworkPage.edit_network()
		self.take_s2_snapshot()
		network_page = self.LeftPanel.go_to_network_page()
		self.NetworkPage.assert_new_network()
		self.NetworkPage.delete_network_if_present()
		self.take_s3_snapshot()
		self.assert_s1_s2_diff(0)
		self.assert_s1_s3_diff()
		self.clear()

	def test_ath_9406_create_personal_wpa_2_personal_voice_network_with_broadcast_filtering_dtim_in(self):
		self.NetworkPage.delete_network_if_present()
		self.take_s1_snapshot()
		basic_info = self.NetworkPage.create_new_network()
		vlan_obj = basic_info.voice_network_info_with_advanced_settings_broadcasefiltering_dtiminterval()
		security = vlan_obj.set_static_vlan_defaults()
		access = security.enable_80211r_roaming()
		access.finish_network_setup()
		self.NetworkPage.assert_new_network()
		edit_network_page = self.NetworkPage.edit_network()
		edit_network_page.click_advanced_settings_accordion()
		edit_network_page.assert_broadcasefiltering_dtiminterval('ARP' , '3 beacons')
		edit_network_page.click_vlans_accordion()
		edit_network_page.click_security_accordion()
		edit_network_page.check_security_configurations()
		self.take_s2_snapshot()
		network_page = self.LeftPanel.go_to_network_page()
		self.NetworkPage.assert_new_network()
		self.NetworkPage.delete_network_if_present()
		self.LeftPanel.assert_delta_config_icon()
		self.take_s3_snapshot()
		self.assert_s1_s2_diff(0)
		self.assert_s1_s3_diff()
		self.clear()


	def test_ath_9407_edit_personal_wpa_2_personal_voice_network_with_broadcast_filtering_dtim_in(self):
		self.NetworkPage.delete_network_if_present()
		self.take_s1_snapshot()
		basic_info = self.NetworkPage.create_new_network()
		vlan_obj = basic_info.voice_network_info_with_advanced_settings_broadcasefiltering_dtiminterval()
		security = vlan_obj.use_vlan_defaults()
		access = security.enable_80211r_roaming()
		access.finish_network_setup()
		self.NetworkPage.assert_new_network()
		edit_network_page = self.NetworkPage.edit_network()
		edit_network_page.click_advanced_settings_accordion()
		edit_network_page.assert_broadcasefiltering_dtiminterval('ARP' , '3 beacons')
		edit_network_page.edit_advanced_settings()
		edit_network_page.click_security_accordion()
		edit_network_page.check_security_configurations()
		edit_network_page.edit_security_configurations()
		self.NetworkPage.assert_new_network()
		edit_network_page = self.NetworkPage.edit_network()
		edit_network_page.click_advanced_settings_accordion()
		edit_network_page.assert_broadcasefiltering_dtiminterval('ALL' , '7 beacons')
		edit_network_page.click_security_accordion()
		edit_network_page.check_security_configurations1()
		self.take_s2_snapshot()
		network_page = self.LeftPanel.go_to_network_page()
		self.NetworkPage.assert_new_network()
		self.NetworkPage.delete_network_if_present()
		self.LeftPanel.assert_delta_config_icon()
		self.take_s3_snapshot()
		self.assert_s1_s2_diff(0)
		self.assert_s1_s3_diff()
		self.clear()

	def _delete_external_radius_servers(self):
		self.NetworkPage.delete_network_if_present()
		security_page = self.LeftPanel.go_to_security() 
		security_page.delete_authentication_server()
		security_page.delete_authentication_server2()
		self.LeftPanel.go_to_network_page()
		
	def test_ath_9408_edit_personal_wpa_2_personal_voice_network_with_broadcast_filtering_dtim_interval(self):
		self._delete_external_radius_servers()
		self.take_s1_snapshot()
		basic_info = self.NetworkPage.create_new_network()
		vlan_obj = basic_info.voice_network_with_advanced_settings()
		security = vlan_obj.use_vlan_defaults()
		security.enable_mac_authentication()
		access = security.click_on_next()
		access.finish_network_setup()
		self.NetworkPage.assert_new_network()
		edit_network_page = self.NetworkPage.edit_network()
		edit_network_page.click_advanced_settings_accordion()
		edit_network_page.edit_advanced_settings_default()
		edit_network_page.click_security_accordion()
		edit_network_page.create_external_radiuds_server('1')
		edit_network_page._save_settings()
		self.NetworkPage.assert_new_network()
		edit_network_page = self.NetworkPage.edit_network()
		edit_network_page.click_advanced_settings_accordion()
		edit_network_page.assert_broadcasefiltering_dtiminterval('Disabled' , '1 beacon')
		edit_network_page.click_security_accordion()
		edit_network_page.check_security_configurations_for_external_radius_server()
		self.take_s2_snapshot()
		network_page = self.LeftPanel.go_to_network_page()
		self.NetworkPage.assert_new_network()
		self._delete_external_radius_servers()
		self.LeftPanel.assert_delta_config_icon()
		self.take_s3_snapshot()
		self.assert_s1_s2_diff(0)
		self.assert_s1_s3_diff()
		self.clear()

	def test_ath_9409_edit_personal_wpa_2_personal_voice_network_with_authentication_server_2_delim(self):
		self._delete_external_radius_servers()
		self.take_s1_snapshot()
		basic_info = self.NetworkPage.create_new_network()
		vlan_obj = basic_info.voice_network_info()
		security = vlan_obj.use_vlan_defaults()
		security.enable_mac_authentication()
		access = security.click_on_next()
		access.finish_network_setup()
		self.NetworkPage.assert_new_network()
		edit_network_page = self.NetworkPage.edit_network()
		edit_network_page.click_security_accordion()
		edit_network_page.create_external_radiuds_server('1')
		edit_network_page.create_external_radiuds_server('2')
		edit_network_page.edit_security_configurations_external_radiuds_server2()
		self.NetworkPage.assert_new_network()
		edit_network_page = self.NetworkPage.edit_network()
		edit_network_page.click_security_accordion()
		edit_network_page.check_security_configurations_for_external_radius_server2()
		self.take_s2_snapshot()
		network_page = self.LeftPanel.go_to_network_page()
		self.NetworkPage.assert_new_network()
		self._delete_external_radius_servers()
		self.LeftPanel.assert_delta_config_icon()
		self.take_s3_snapshot()
		self.assert_s1_s2_diff(0)
		self.assert_s1_s3_diff()
		self.clear()

	def test_ath_9410_edit_personal_wpa_2_personal_voice_network_with_dynamic_multicast_optimizationself(self):
		self._delete_external_radius_servers()
		self.take_s1_snapshot()
		basic_info = self.NetworkPage.create_new_network()
		vlan_obj = basic_info.voice_network_info()
		security = vlan_obj.use_vlan_defaults()
		security.enable_mac_authentication()
		security.create_external_radiuds_server('1')
		security.create_external_radiuds_server('2')
		security.configure_auth_server_settings(uppercase_support = True)
		security.set_delimiter()
		access = security.click_on_next()
		access.finish_network_setup()
		self.NetworkPage.assert_new_network()
		edit_network_page = self.NetworkPage.edit_network()
		edit_network_page.click_advanced_settings_accordion()
		edit_network_page.enable_optimization_feilds()
		edit_network_page.click_security_accordion()
		edit_network_page.edit_personal_employee_network_with_dynamic_multicast_optimization()
		self.NetworkPage.assert_new_network()
		edit_network_page = self.NetworkPage.edit_network()
		edit_network_page.click_advanced_settings_accordion()
		edit_network_page.check_enable_optimization_feilds()
		edit_network_page.click_security_accordion()
		edit_network_page.check_personal_employee_network_with_dynamic_multicast_optimization()
		self.take_s2_snapshot()
		network_page = self.LeftPanel.go_to_network_page()
		self.NetworkPage.assert_new_network()
		self._delete_external_radius_servers()
		self.LeftPanel.assert_delta_config_icon()
		self.take_s3_snapshot()
		self.assert_s1_s2_diff(0)
		self.assert_s1_s3_diff()
		self.clear()
		
	def test_ath_9414_create_personal_wpa_personal_voice_network_with_background_wmm_share_virtual(self):
		self.NetworkPage.delete_network_if_present()
		self.take_s1_snapshot()
		basic_info = self.NetworkPage.create_new_network()
		vlan_obj = basic_info.voice_network_with_advanced_settings_background_wmm()
		security = vlan_obj.use_vlan_defaults()
		access = security.set_wpa_blacklisting_enable()
		access.finish_network_setup()
		self.NetworkPage.assert_new_network()
		edit_network_page = self.NetworkPage.edit_network()
		edit_network_page.click_security_accordion()
		edit_network_page.check_wpa_blacklisting_enable()
		self.take_s2_snapshot()
		network_page = self.LeftPanel.go_to_network_page()
		self.NetworkPage.assert_new_network()
		self.NetworkPage.delete_network_if_present()
		self.LeftPanel.assert_delta_config_icon()
		self.take_s3_snapshot()
		self.assert_s1_s2_diff(0)
		self.assert_s1_s3_diff()
		self.clear()
		
	def test_ath_9415_edit_personal_wpa_personal_voice_network_with_background_wmm_share_Blacklistist(self):
		self.NetworkPage.delete_network_if_present()
		self.take_s1_snapshot()
		basic_info = self.NetworkPage.create_new_network()
		vlan_obj = basic_info.voice_network_with_advanced_settings_background_wmm()
		security = vlan_obj.use_vlan_defaults()
		access = security.set_wpa_blacklisting_enable()
		access.finish_network_setup()
		self.NetworkPage.assert_new_network()
		edit_network_page = self.NetworkPage.edit_network()
		edit_network_page.click_advanced_settings_accordion()
		edit_network_page.edit_background_wmm_default()
		edit_network_page.click_security_accordion()
		edit_network_page.edit_wpa_blacklisting_disable()
		self.NetworkPage.assert_new_network()
		edit_network_page = self.NetworkPage.edit_network()
		edit_network_page.click_security_accordion()
		edit_network_page.check_wpa_blacklisting_disable()
		self.take_s2_snapshot()
		network_page = self.LeftPanel.go_to_network_page()
		self.NetworkPage.assert_new_network()
		self.NetworkPage.delete_network_if_present()
		self.LeftPanel.assert_delta_config_icon()
		self.take_s3_snapshot()
		self.assert_s1_s2_diff(0)
		self.assert_s1_s3_diff()
		self.clear()
		
	def test_ath_9416_edit_personal_wpa_2_personal_voice_network_with_best_effort_wmm_share_static(self):
		self._delete_external_radius_servers()
		self.take_s1_snapshot()
		basic_info = self.NetworkPage.create_new_network()
		vlan_obj = basic_info.voice_network_info()
		security = vlan_obj.use_vlan_defaults()
		access = security.assert_roaming_defaults(True,False)
		access.finish_network_setup()
		self.NetworkPage.assert_new_network()
		edit_network_page = self.NetworkPage.edit_network()
		edit_network_page.click_advanced_settings_accordion()
		edit_network_page.set_besteffort_wmm_share()
		edit_network_page.click_vlans_accordion()
		edit_network_page.set_static_vlan()
		edit_network_page.click_security_accordion()
		edit_network_page.enable_mac_authentication()
		edit_network_page.create_external_radiuds_server('1')
		edit_network_page.create_external_radiuds_server('2')
		edit_network_page._save_settings()
		self.NetworkPage.assert_new_network()
		edit_network_page = self.NetworkPage.edit_network()
		edit_network_page.click_security_accordion()
		edit_network_page.check_security_configurations_for_two_external_radius_servers()
		self.take_s2_snapshot()
		network_page = self.LeftPanel.go_to_network_page()
		self.NetworkPage.assert_new_network()
		self._delete_external_radius_servers()
		self.LeftPanel.assert_delta_config_icon()
		self.take_s3_snapshot()
		self.assert_s1_s2_diff(0)
		self.assert_s1_s3_diff()
		self.clear()

	def test_ath_9417_edit_personal_wpa_2_personal_voice_network_with_best_effort_wmm_share_default(self):
		self._delete_external_radius_servers()
		self.take_s1_snapshot()
		basic_info = self.NetworkPage.create_new_network()
		vlan_obj = basic_info.voice_network_with_advanced_settings_besteffort_wmm_share()
		security = vlan_obj.use_vlan_defaults()
		access = security.enable_mac_authentication()
		security.create_external_radiuds_server('1')
		access = security.click_on_next()
		access.finish_network_setup()
		self.NetworkPage.assert_new_network()
		edit_network_page = self.NetworkPage.edit_network()
		edit_network_page.click_advanced_settings_accordion()
		edit_network_page.set_besteffort_wmm_share_default()
		edit_network_page.click_vlans_accordion()
		edit_network_page.click_security_accordion()
		edit_network_page.select_internalserver()
		edit_network_page.checking_for_authentication_server2_visibility()
		edit_network_page._save_settings()
		self.NetworkPage.assert_new_network()
		edit_network_page = self.NetworkPage.edit_network()
		edit_network_page.click_vlans_accordion()
		edit_network_page.click_security_accordion()
		edit_network_page.checking_for_authentication_server()
		edit_network_page.checking_for_authentication_server2_visibility()
		self.take_s2_snapshot()
		network_page = self.LeftPanel.go_to_network_page()
		self.NetworkPage.assert_new_network()
		self._delete_external_radius_servers()
		self.take_s3_snapshot()
		self.assert_s1_s2_diff(0)
		self.assert_s1_s3_diff()
		self.clear()
		
	def test_ath_9418_create_personal_wpa_2_personal_voice_network_with_video_wmm_share(self):
		self.NetworkPage.delete_network_if_present()
		self.take_s1_snapshot()
		basic_info = self.NetworkPage.create_new_network()
		vlan_obj = basic_info.voice_network_with_advanced_settings_video_wmm_share()
		security = vlan_obj.use_vlan_defaults()
		access = security.set_both_wpa_2_wpa_passphrase_format_64_hexadecimal_chars()
		access.finish_network_setup()
		self.NetworkPage.assert_new_network()
		edit_network_page = self.NetworkPage.edit_network()
		edit_network_page.click_security_accordion()
		edit_network_page.checking_key_wpa_2_and_wpa_64_passphrase_format()
		self.take_s2_snapshot()
		network_page = self.LeftPanel.go_to_network_page()
		self.NetworkPage.assert_new_network()
		self.NetworkPage.delete_network_if_present()
		self.LeftPanel.assert_delta_config_icon()
		self.take_s3_snapshot()
		self.assert_s1_s2_diff(0)
		self.assert_s1_s3_diff()
		
	def test_ath_9420_create_personal_static_wep_voice_network_with_voice_wmm_share_key_management(self):
		self.NetworkPage.delete_network_if_present()
		self.take_s1_snapshot()
		basic_info = self.NetworkPage.create_new_network()
		vlan_obj = basic_info.voice_network_with_advanced_settings_voice_wmm_share()
		security = vlan_obj.use_vlan_defaults()
		security.set_static_wep_Tx_key()
		access = security.click_on_next()
		access.finish_network_setup()
		self.NetworkPage.assert_new_network()
		edit_network_page = self.NetworkPage.edit_network()
		edit_network_page.click_security_accordion()
		edit_network_page.check_static_wep_Tx_key()
		self.take_s2_snapshot()
		network_page = self.LeftPanel.go_to_network_page()
		self.NetworkPage.assert_new_network()
		self.NetworkPage.delete_network_if_present()
		self.LeftPanel.assert_delta_config_icon()
		self.take_s3_snapshot()
		self.assert_s1_s2_diff(0)
		self.assert_s1_s3_diff()
		self.clear()
		
	def test_ath_9421_edit_personal_static_wep_voice_network_with_voice_wmm_share(self):
		self._delete_external_radius_servers()
		self.take_s1_snapshot()
		basic_info = self.NetworkPage.create_new_network()
		vlan_obj = basic_info.voice_network_with_advanced_settings_voice_wmm_share()
		security = vlan_obj.use_vlan_defaults()
		security.enable_mac_authentication()
		security.create_external_radiuds_server('1')
		security.set_static_wep_Tx_key()
		access = security.click_on_next()
		access.finish_network_setup()
		self.NetworkPage.assert_new_network()
		edit_network_page = self.NetworkPage.edit_network()
		edit_network_page.click_advanced_settings_accordion()
		edit_network_page.edit_voice_wmm_share_default()
		edit_network_page.click_security_accordion()
		edit_network_page.edit_static_wep_network()
		self.NetworkPage.assert_new_network()
		edit_network_page = self.NetworkPage.edit_network()
		edit_network_page.click_security_accordion()
		edit_network_page.check_static_network_changes()
		self.take_s2_snapshot()
		network_page = self.LeftPanel.go_to_network_page()
		self.NetworkPage.assert_new_network()
		self.NetworkPage.delete_network_if_present()
		self._delete_external_radius_servers()
		self.LeftPanel.assert_delta_config_icon()
		self.take_s3_snapshot()
		self.assert_s1_s2_diff(0)
		self.assert_s1_s3_diff()
		self.clear()
		
	def test_ath_9423_create_personal_wpa_2_personal_voice_network_with_content_filtering_key(self):
		self.NetworkPage.delete_network_if_present()
		self.take_s1_snapshot()
		basic_info = self.NetworkPage.create_new_network()
		vlan_obj = basic_info.voice_network_with_advanced_settings_enable_content_filtering()
		security = vlan_obj.use_vlan_defaults()
		access = security.enable_80211r_roaming()
		access.finish_network_setup()
		self.NetworkPage.assert_new_network()
		edit_network_page = self.NetworkPage.edit_network()
		edit_network_page.click_security_accordion()
		edit_network_page.check_security_configurations()
		self.take_s2_snapshot()
		network_page = self.LeftPanel.go_to_network_page()
		self.NetworkPage.assert_new_network()
		self.NetworkPage.delete_network_if_present()
		self.LeftPanel.assert_delta_config_icon()
		self.take_s3_snapshot()
		self.assert_s1_s2_diff(0)
		self.assert_s1_s3_diff()
		
	def test_ath_9427_edit_personal_wpa_2_personal_voice_network_with_band_key_management(self):
		self.NetworkPage.delete_network_if_present()
		self.take_s1_snapshot()
		basic_info = self.NetworkPage.create_new_network()
		vlan_obj = basic_info.voice_network_with_advanced_settings_5ghz_band()
		security = vlan_obj.use_vlan_defaults()
		security.set_security_level_and_key_management('Personal')
		access = security.click_on_next()
		access.finish_network_setup()
		self.NetworkPage.assert_new_network()
		edit_network_page = self.NetworkPage.edit_network()
		edit_network_page.click_advanced_settings_accordion()
		edit_network_page.set_band_default()
		edit_network_page.click_security_accordion()
		edit_network_page.edit_network_wpa_2_personal()
		edit_network_page.checking_for_wep_key_visibility()
		edit_network_page._save_settings()
		self.NetworkPage.assert_new_network()
		edit_network_page = self.NetworkPage.edit_network()
		edit_network_page.click_advanced_settings_accordion()
		edit_network_page.checking_for_band_all()
		edit_network_page.click_security_accordion()
		edit_network_page.checking_network_wpa_2_personal()
		self.take_s2_snapshot()
		network_page = self.LeftPanel.go_to_network_page()
		self.NetworkPage.assert_new_network()
		self.NetworkPage.delete_network_if_present()
		self.LeftPanel.assert_delta_config_icon()
		self.take_s3_snapshot()
		self.assert_s1_s2_diff(0)
		self.assert_s1_s3_diff()
		self.clear()
		
	def test_ath_9422_edit_personal_static_wep_voice_network_with_content_filtering_blacklisting_mac_authentication(self):
		self.NetworkPage.delete_network_if_present()
		self.take_s1_snapshot()
		basic_info = self.NetworkPage.create_new_network()
		vlan_obj = basic_info.voice_network_info()
		security = vlan_obj.use_vlan_defaults()
		security.set_static_wep_Tx_key()
		security.configure_auth_server_settings(blacklisting=True)
		security.create_external_radius_server_in_auth_server_one()
		security.set_reauth_interval()
		access = security.click_on_next()
		access.finish_network_setup()
		edit_network = self.NetworkPage.edit_network()
		edit_network.edit_personal_static_wep_voice_network_with_content_filtering_blacklisting()
		self.LeftPanel.assert_delta_config_icon()
		edit_network = self.NetworkPage.edit_network()
		edit_network.assert_personal_static_wep_voice_network_with_content_filtering_blacklisting()
		self.LeftPanel.go_to_network_page()
		self.take_s2_snapshot()
		self._delete_network_auth_server()
		self.take_s3_snapshot()
		self.assert_s1_s2_diff(0)
		self.assert_s1_s3_diff()
		self.clear()
		
	def test_ath_9424_edit_personal_wpa_personal_voice_network_with_content_filtering_key_management(self):
		self.take_s1_snapshot()
		conf = self.config.config_vars
		self._delete_network_auth_server()
		basic_info = self.NetworkPage.create_new_network()		
		virtual_lan = basic_info.voice_network_with_advanced_settings_enable_content_filtering()
		security = virtual_lan.use_vlan_defaults()
		access = security.configure_employee_security()
		access.finish_network_setup()
		edit_network_page = self.NetworkPage.edit_network()
		edit_network_page.click_advanced_settings_accordion()
		edit_network_page.content_filtering_dropdown.set(conf.content_filtering_disabled)
		edit_network_page.change_key_management()
		self.LeftPanel.assert_delta_config_icon()
		edit_network_page = self.NetworkPage.edit_network()
		edit_network_page.click_advanced_settings_accordion()
		self.browser.assert_drop_down_value(edit_network_page.content_filtering_dropdown, conf.content_filtering_disabled, "Content Filtering is not set 'Enabled'")
		edit_network_page.security_accordion.click()
		self.browser.assert_drop_down_value(edit_network_page.security_key_management, conf.key_management_value, "Key management is not set to 'WPA personal'")
		self.LeftPanel.go_to_network_page()
		self.take_s2_snapshot()
		self._delete_network_auth_server()
		self.take_s3_snapshot()
		self.assert_s1_s2_diff(0)
		self.assert_s1_s3_diff()
		self.clear()
		
	def test_ath_9425_edit_personal_both_wpa2_and_wpa_personal_voice_network_with_band_key_management_mac_authentication(self):
		self.take_s1_snapshot()
		conf = self.config.config_vars
		self._delete_network_auth_server()
		basic_info = self.NetworkPage.create_new_network()
		basic_info.voice_network_info_with_advanced_settings()
		virtual_lan = basic_info.click_on_next()	
		security = virtual_lan.use_vlan_defaults()
		access = security.set_key_management_wpa_personal() 
		access.finish_network_setup()
		edit_network_page = self.NetworkPage.edit_network()
		edit_network_page.change_advanced_band_settings()
		edit_network_page = self.NetworkPage.edit_network()
		edit_network_page.change_key_management_to_both_wpa2_wpa_personal()
		self.LeftPanel.assert_delta_config_icon()
		edit_network_page = self.NetworkPage.edit_network()
		edit_network_page.click_advanced_settings_accordion()
		self.browser.assert_drop_down_value(edit_network_page.band, conf.band_value, "Band is not set to 2.4 GHz")
		edit_network_page.security_accordion.click()
		self.browser.assert_drop_down_value(edit_network_page.security_key_management, conf.new_key_management_value, "Key management is not set to 'Both WPA & WPA2 personal'")
		self.browser.assert_drop_down_value(edit_network_page.mac_authentication, conf.mac_authentication_value, "MAC authentication is not set to 'Enabled'")
		self.LeftPanel.go_to_network_page()
		self.take_s2_snapshot()
		self._delete_network_auth_server()
		self.take_s3_snapshot()
		self.assert_s1_s2_diff(0)
		self.assert_s1_s3_diff()
		self.clear()		
		
	def test_ath_9426_edit_personal_static_wep_voice_network_with_band_key_management_wep_key_802_11_r_roaming(self):
		self.take_s1_snapshot()
		conf = self.config.config_vars
		self._delete_network_auth_server()
		basic_info = self.NetworkPage.create_new_network()
		basic_info.voice_network_info_with_advanced_settings()
		basic_info.set_24ghz_band()
		virtual_lan = basic_info.click_on_next()	
		security = virtual_lan.use_vlan_defaults()
		security.set_open_roaming_nondefault()
		access = security.configure_employee_security(True)
		access.finish_network_setup()
		edit_network_page = self.NetworkPage.edit_network()
		edit_network_page.change_advanced_band_settings_5_ghz()
		edit_network_page.security_accordion.click()
		edit_network_page.security_key_management.set(self.config.config_vars.static_wep_value)
		edit_network_page.wep_key.set(self.config.config_vars.wep_key)
		edit_network_page.wep_key_retype.set(self.config.config_vars.wep_key)
		edit_network_page.save_settings.click()
		self.LeftPanel.assert_delta_config_icon()
		edit_network_page = self.NetworkPage.edit_network()
		edit_network_page.click_advanced_settings_accordion()
		self.browser.assert_drop_down_value(edit_network_page.band, conf.band_value_5ghz, "Band is not set to 5 GHz")
		edit_network_page.security_accordion.click()
		self.browser.assert_drop_down_value(edit_network_page.security_key_management, conf.static_wep_value, "Key management is not set to 'Static WEP'")
		self.LeftPanel.go_to_network_page()
		self.take_s2_snapshot()
		self._delete_network_auth_server()
		self.take_s3_snapshot()
		self.assert_s1_s2_diff(0)
		self.assert_s1_s3_diff()
		self.clear()
		
		
	def test_ath_9413_edit_personal_wpa2_personal_enterprise_voice_network_with_2_4ghz_5ghz(self):
		self._delete_network_auth_server()
		conf = self.config.config_vars
		self.take_s1_snapshot()
		basic_info = self.NetworkPage.create_new_network()
		virtual_lan = basic_info.set_advance_options()
		security = virtual_lan.use_vlan_defaults()
		security.configure_security_level()
		security.enable_mac_authentication1()
		security.create_external_radiuds_server('1')
		security.create_external_radiuds_server('2')
		security.enable_accounting_interval('60')
		security.set_load_balancing_field(conf.blacklisting_option)
		security.configure_reauth_interval(conf.max_authentication_failure,conf.reauth_intrvl_unit_min)
		security.set_valid_paasphrase_retype()
		access = security.click_on_next()        
		access.finish_network_setup()
		edit_network_page = self.NetworkPage.edit_network()
		edit_network_page.click_advanced_settings_accordion()
		edit_network_page.set_2_4ghz_max_min_transmit_rates(conf.max_auth_failure_invalid_num,conf.max_value_36)
		edit_network_page.set_5ghz_max_min_transmit_rates(conf.min_value_9,conf.max_value_48)
		edit_network_page.open_security_accordion()
		edit_network_page.configure_mac_authentication()
		edit_network_page.save_configuration()
		self.LeftPanel.assert_delta_config_icon()
		edit_network = self.NetworkPage.edit_network()
		edit_network.assert_edit_personal_both_wpa2_personal_enterprise_voice_network_with_2_4ghz_5ghz()
		self.take_s2_snapshot()
		self.LeftPanel.go_to_network_page()
		self._delete_network_auth_server()
		self.take_s3_snapshot()
		self.assert_s1_s2_diff(0)
		self.assert_s1_s3_diff()
		self.clear()
	
	def _delete_network_auth_server(self):
		'''
		Delete wireless and auth servers 
		'''
		self.NetworkPage.delete_network_if_present()
		security_page = self.LeftPanel.go_to_security() 
		security_page.delete_authentication_server()
		security_page.delete_authentication_server2()
		self.LeftPanel.go_to_network_page()	
		
	def test_ath_12024_create_personal_wpa_2_personal_voice_network_with_passphrase(self):
		self.NetworkPage.delete_network_if_present()
		self.take_s1_snapshot()
		basic_info = self.NetworkPage.create_new_network()
		vlan_obj = basic_info.voice_network_info()
		security = vlan_obj.use_vlan_defaults()
		security.set_security_key_management('WPA-2 Personal')
		security.add_pass_phrase_Personal_8_63()
		access = security.click_on_next()
		access.finish_network_setup()
		self.LeftPanel.go_to_network_page()
		self.LeftPanel.assert_delta_config_icon()
		self.NetworkPage.assert_new_network()
		edit_network_page = self.NetworkPage.edit_network()
		edit_network_page.assert_primary_usage_voice()
		edit_network_page.click_security_accordion()

		self.take_s2_snapshot()
		network_page = self.LeftPanel.go_to_network_page()
		self.NetworkPage.assert_new_network()
		self.NetworkPage.delete_network_if_present()
		self.take_s3_snapshot()
		self.assert_s1_s2_diff(0)
		self.assert_s1_s3_diff()
		self.clear()

	def test_ath_12025_create_personal_wpa_2_personal_voice_network_with_broadcast_filtering_dtim_in(self):
		self.NetworkPage.delete_network_if_present()
		self.take_s1_snapshot()
		basic_info = self.NetworkPage.create_new_network()
		vlan_obj = basic_info.voice_network_info_with_advanced_settings_broadcasefiltering_dtiminterval()
		security = vlan_obj.set_static_vlan_defaults()
		access = security.enable_80211r_roaming()
		access.finish_network_setup()
		self.NetworkPage.assert_new_network()
		edit_network_page = self.NetworkPage.edit_network()
		edit_network_page.click_advanced_settings_accordion()
		edit_network_page.assert_broadcasefiltering_dtiminterval('ARP' , '3 beacons')
		edit_network_page.click_vlans_accordion()
		edit_network_page.click_security_accordion()
		edit_network_page.check_security_configurations()
		self.take_s2_snapshot()
		network_page = self.LeftPanel.go_to_network_page()
		self.NetworkPage.assert_new_network()
		self.NetworkPage.delete_network_if_present()
		self.LeftPanel.assert_delta_config_icon()
		self.take_s3_snapshot()
		self.assert_s1_s2_diff(0)
		self.assert_s1_s3_diff()
		self.clear()

	def test_ath_12026_edit_personal_wpa_2_personal_voice_network_with_broadcast_filtering_dtim_in(self):
		self.NetworkPage.delete_network_if_present()
		self.take_s1_snapshot()
		basic_info = self.NetworkPage.create_new_network()
		vlan_obj = basic_info.voice_network_info_with_advanced_settings_broadcasefiltering_dtiminterval()
		security = vlan_obj.use_vlan_defaults()
		access = security.enable_80211r_roaming()
		access.finish_network_setup()
		self.NetworkPage.assert_new_network()
		edit_network_page = self.NetworkPage.edit_network()
		edit_network_page.click_advanced_settings_accordion()
		edit_network_page.assert_broadcasefiltering_dtiminterval('ARP' , '3 beacons')
		edit_network_page.edit_advanced_settings()
		edit_network_page.click_security_accordion()
		edit_network_page.check_security_configurations()
		edit_network_page.edit_security_configurations()
		self.NetworkPage.assert_new_network()
		edit_network_page = self.NetworkPage.edit_network()
		edit_network_page.click_advanced_settings_accordion()
		edit_network_page.assert_broadcasefiltering_dtiminterval('ALL' , '7 beacons')
		edit_network_page.click_security_accordion()
		edit_network_page.check_security_configurations1()
		self.take_s2_snapshot()
		network_page = self.LeftPanel.go_to_network_page()
		self.NetworkPage.assert_new_network()
		self.NetworkPage.delete_network_if_present()
		self.LeftPanel.assert_delta_config_icon()
		self.take_s3_snapshot()
		self.assert_s1_s2_diff(0)
		self.assert_s1_s3_diff()
		self.clear()
		
	def test_ath_12027_edit_personal_wpa_2_personal_voice_network_with_broadcast_filtering_dtim_interval(self):
		self._delete_external_radius_servers()
		self.take_s1_snapshot()
		basic_info = self.NetworkPage.create_new_network()
		vlan_obj = basic_info.voice_network_with_advanced_settings()
		security = vlan_obj.use_vlan_defaults()
		security.enable_mac_authentication()
		access = security.click_on_next()
		access.finish_network_setup()
		self.NetworkPage.assert_new_network()
		edit_network_page = self.NetworkPage.edit_network()
		edit_network_page.click_advanced_settings_accordion()
		edit_network_page.edit_advanced_settings_default()
		edit_network_page.click_security_accordion()
		edit_network_page.create_external_radiuds_server('1')
		edit_network_page._save_settings()
		self.NetworkPage.assert_new_network()
		edit_network_page = self.NetworkPage.edit_network()
		edit_network_page.click_advanced_settings_accordion()
		edit_network_page.assert_broadcasefiltering_dtiminterval('Disabled' , '1 beacon')
		edit_network_page.click_security_accordion()
		edit_network_page.check_security_configurations_for_external_radius_server()
		self.take_s2_snapshot()
		network_page = self.LeftPanel.go_to_network_page()
		self.NetworkPage.assert_new_network()
		self._delete_external_radius_servers()
		self.LeftPanel.assert_delta_config_icon()
		self.take_s3_snapshot()
		self.assert_s1_s2_diff(0)
		self.assert_s1_s3_diff()
		self.clear()

	def test_ath_12028_edit_personal_wpa_2_personal_voice_network_with_authentication_server_2_delim(self):
		self._delete_external_radius_servers()
		self.take_s1_snapshot()
		basic_info = self.NetworkPage.create_new_network()
		vlan_obj = basic_info.voice_network_info()
		security = vlan_obj.use_vlan_defaults()
		security.enable_mac_authentication()
		access = security.click_on_next()
		access.finish_network_setup()
		self.NetworkPage.assert_new_network()
		edit_network_page = self.NetworkPage.edit_network()
		edit_network_page.click_security_accordion()
		edit_network_page.create_external_radiuds_server('1')
		edit_network_page.create_external_radiuds_server('2')
		edit_network_page.edit_security_configurations_external_radiuds_server2()
		self.NetworkPage.assert_new_network()
		edit_network_page = self.NetworkPage.edit_network()
		edit_network_page.click_security_accordion()
		edit_network_page.check_security_configurations_for_external_radius_server2()
		self.take_s2_snapshot()
		network_page = self.LeftPanel.go_to_network_page()
		self.NetworkPage.assert_new_network()
		self._delete_external_radius_servers()
		self.LeftPanel.assert_delta_config_icon()
		self.take_s3_snapshot()
		self.assert_s1_s2_diff(0)
		self.assert_s1_s3_diff()
		self.clear()

	def test_ath_12029_edit_personal_wpa_2_personal_voice_network_with_dynamic_multicast_optimizationself(self):
		self._delete_external_radius_servers()
		conf = self.config.config_vars
		self.take_s1_snapshot()
		basic_info = self.NetworkPage.create_new_network()
		vlan_obj = basic_info.voice_network_dmo_channel_utilization_and_multicast_transmission(network = 'Voice',channel = conf.background_wmm)
		security = vlan_obj.use_vlan_defaults()
		security.enable_mac_authentication()
		security.create_external_radiuds_server('1')
		security.create_external_radiuds_server('2')
		security.configure_auth_server_settings(uppercase_support = True)
		security.set_delimiter()
		access = security.click_on_next()
		access.finish_network_setup()
		self.NetworkPage.assert_new_network()
		edit_network_page = self.NetworkPage.edit_network()
		edit_network_page.click_advanced_settings_accordion()
		edit_network_page.enable_optimization_feilds()
		edit_network_page.click_security_accordion()
		edit_network_page.edit_personal_employee_network_with_dynamic_multicast_optimization()
		self.NetworkPage.assert_new_network()
		edit_network_page = self.NetworkPage.edit_network()
		edit_network_page.click_advanced_settings_accordion()
		edit_network_page.check_enable_optimization_feilds()
		edit_network_page.click_security_accordion()
		edit_network_page.check_personal_employee_network_with_dynamic_multicast_optimization()
		self.take_s2_snapshot()
		network_page = self.LeftPanel.go_to_network_page()
		self.NetworkPage.assert_new_network()
		self._delete_external_radius_servers()
		self.LeftPanel.assert_delta_config_icon()
		self.take_s3_snapshot()
		self.assert_s1_s2_diff(0)
		self.assert_s1_s3_diff()
		self.clear()
		
	def test_ath_12030_edit_personal_wpa_2_personal_voice_network_with_airtime_value_each_radio(self):
		self._delete_network_auth_server()
		self.take_s1_snapshot()
		basic_info = self.NetworkPage.create_new_network()
		virtual_lan = basic_info.voice_network_dmo_channel_utilization_and_multicast_transmission('Voice',self.config.config_vars.background_wmm,'Enabled')
		security = virtual_lan.use_vlan_defaults()
		security.set_security_key_management('WPA-2 Personal')
		security.enable_mac_authentication()
		security.create_external_radius_server_in_auth_server_one()
		security.create_external_radius_server_in_auth_server_two()	
		security.enable_accounting_interval(self.config.config_vars.valid_accounting)
		access = security.click_on_next()
		access.finish_network_setup()
		edit_network = self.NetworkPage.edit_network()
		edit_network.edit_wpa_2_personal_voice_network_with_airtime_each_radio_value()
		self.LeftPanel.assert_delta_config_icon()
		edit_network = self.NetworkPage.edit_network()
		edit_network.assert_wpa_2_personal_voice_network_with_airtime_each_radio_value()
		self.LeftPanel.go_to_network_page()
		self.take_s2_snapshot()
		self._delete_network_auth_server()
		self.take_s3_snapshot()
		self.assert_s1_s2_diff(0)
		self.assert_s1_s3_diff()
		self.clear()
		
	def test_ath_12031_edit_personal_wpa_2_personal_voice_network_with_airtime_dmo_channel_utilization(self):
		'''
			In test case 9412. 
			In Precondition it says set the Authentication Server 2 : InternalServer and Accounting : Disabled.
			But, when we will select Authentication Server 2 to 'InternalServer' then the Accounting field will invisible.
			But by default Accounting field is 'Disabled.' , so we escape this step.
		'''
		self._delete_network_auth_server()
		self.take_s1_snapshot()
		basic_info = self.NetworkPage.create_new_network()
		virtual_lan = basic_info.voice_network_dmo_channel_dynamic_optimization_radio_airtime('Voice',self.config.config_vars.edit_besteffort)
		security = virtual_lan.use_vlan_defaults()
		security.set_security_key_management('WPA-2 Personal')
		security.enable_mac_authentication()
		security.create_external_radius_server_in_auth_server_one()
		security.create_external_radius_server_in_auth_server_two()
		security.set_authentication_server_2_value(self.config.config_vars.edit_Authentication_server)
		access = security.click_on_next()
		access.finish_network_setup()
		edit_network = self.NetworkPage.edit_network()
		edit_network.edit_wpa_2_personal_voice_network_with_airtime_dmo_channel_value()
		self.LeftPanel.assert_delta_config_icon()
		edit_network = self.NetworkPage.edit_network()
		edit_network.assert_wpa_2_personal_voice_network_with_airtime_dmo_channel_value()
		self.LeftPanel.go_to_network_page()
		self.take_s2_snapshot()
		self._delete_network_auth_server()
		self.take_s3_snapshot()
		self.assert_s1_s2_diff(0)
		self.assert_s1_s3_diff()
		self.clear()
		
	def test_ath_12032_edit_personal_wpa2_personal_enterprise_voice_network_with_2_4ghz_5ghz(self):
		self._delete_network_auth_server()
		conf = self.config.config_vars
		self.take_s1_snapshot()
		basic_info = self.NetworkPage.create_new_network()
		virtual_lan = basic_info.set_advance_options()
		security = virtual_lan.use_vlan_defaults()
		security.configure_security_level()
		security.enable_mac_authentication1()
		security.create_external_radiuds_server('1')
		security.create_external_radiuds_server('2')
		security.enable_accounting_interval('60')
		security.set_load_balancing_field(conf.blacklisting_option)
		security.configure_reauth_interval(conf.max_authentication_failure,conf.reauth_intrvl_unit_min)
		security.set_valid_paasphrase_retype()
		access = security.click_on_next()        
		access.finish_network_setup()
		edit_network_page = self.NetworkPage.edit_network()
		edit_network_page.click_advanced_settings_accordion()
		edit_network_page.set_2_4ghz_max_min_transmit_rates(conf.max_auth_failure_invalid_num,conf.max_value_36)
		edit_network_page.set_5ghz_max_min_transmit_rates(conf.min_value_9,conf.max_value_48)
		edit_network_page.open_security_accordion()
		edit_network_page.configure_mac_authentication()
		edit_network_page.save_configuration()
		self.LeftPanel.assert_delta_config_icon()
		edit_network = self.NetworkPage.edit_network()
		edit_network.assert_edit_personal_both_wpa2_personal_enterprise_voice_network_with_2_4ghz_5ghz()
		self.take_s2_snapshot()
		self.LeftPanel.go_to_network_page()
		self._delete_network_auth_server()
		self.take_s3_snapshot()
		self.assert_s1_s2_diff(0)
		self.assert_s1_s3_diff()
		self.clear()
		
	def test_ath_12033_create_personal_wpa_personal_voice_network_with_background_wmm_share_virtual(self):
		self.NetworkPage.delete_network_if_present()
		self.take_s1_snapshot()
		basic_info = self.NetworkPage.create_new_network()
		vlan_obj = basic_info.voice_network_with_advanced_settings_background_wmm()
		security = vlan_obj.use_vlan_defaults()
		access = security.set_wpa_blacklisting_enable()
		access.finish_network_setup()
		self.NetworkPage.assert_new_network()
		edit_network_page = self.NetworkPage.edit_network()
		edit_network_page.click_security_accordion()
		edit_network_page.check_wpa_blacklisting_enable()
		self.take_s2_snapshot()
		network_page = self.LeftPanel.go_to_network_page()
		self.NetworkPage.assert_new_network()
		self.NetworkPage.delete_network_if_present()
		self.LeftPanel.assert_delta_config_icon()
		self.take_s3_snapshot()
		self.assert_s1_s2_diff(0)
		self.assert_s1_s3_diff()
		self.clear()
		
	def test_ath_12034_edit_personal_wpa_personal_voice_network_with_background_wmm_share_Blacklistist(self):
		self.NetworkPage.delete_network_if_present()
		self.take_s1_snapshot()
		basic_info = self.NetworkPage.create_new_network()
		vlan_obj = basic_info.voice_network_with_advanced_settings_background_wmm()
		security = vlan_obj.use_vlan_defaults()
		access = security.set_wpa_blacklisting_enable()
		access.finish_network_setup()
		self.NetworkPage.assert_new_network()
		edit_network_page = self.NetworkPage.edit_network()
		edit_network_page.click_advanced_settings_accordion()
		edit_network_page.edit_background_wmm_default()
		edit_network_page.click_security_accordion()
		edit_network_page.edit_wpa_blacklisting_disable()
		self.NetworkPage.assert_new_network()
		edit_network_page = self.NetworkPage.edit_network()
		edit_network_page.click_security_accordion()
		edit_network_page.check_wpa_blacklisting_disable()
		self.take_s2_snapshot()
		network_page = self.LeftPanel.go_to_network_page()
		self.NetworkPage.assert_new_network()
		self.NetworkPage.delete_network_if_present()
		self.LeftPanel.assert_delta_config_icon()
		self.take_s3_snapshot()
		self.assert_s1_s2_diff(0)
		self.assert_s1_s3_diff()
		self.clear()
		
	def test_ath_9411_edit_personal_wpa_2_personal_voice_network_with_airtime_value_each_radio(self):
		self._delete_network_auth_server()
		self.take_s1_snapshot()
		basic_info = self.NetworkPage.create_new_network()
		virtual_lan = basic_info.voice_network_dmo_channel_utilization_and_multicast_transmission('Voice',self.config.config_vars.background_wmm,'Enabled')
		security = virtual_lan.use_vlan_defaults()
		security.set_security_key_management('WPA-2 Personal')
		security.enable_mac_authentication()
		security.create_external_radius_server_in_auth_server_one()
		security.create_external_radius_server_in_auth_server_two()	
		security.enable_accounting_interval(self.config.config_vars.valid_accounting)
		access = security.click_on_next()
		access.finish_network_setup()
		edit_network = self.NetworkPage.edit_network()
		edit_network.edit_wpa_2_personal_voice_network_with_airtime_each_radio_value()
		self.LeftPanel.assert_delta_config_icon()
		edit_network = self.NetworkPage.edit_network()
		edit_network.assert_wpa_2_personal_voice_network_with_airtime_each_radio_value()
		self.LeftPanel.go_to_network_page()
		self.take_s2_snapshot()
		self._delete_network_auth_server()
		self.take_s3_snapshot()
		self.assert_s1_s2_diff(0)
		self.assert_s1_s3_diff()
		self.clear()
		
	def test_ath_9412_edit_personal_wpa_2_personal_voice_network_with_airtime_dmo_channel_utilization(self):
		'''
			In test case 9412. 
			In Precondition it says set the Authentication Server 2 : InternalServer and Accounting : Disabled.
			But, when we will select Authentication Server 2 to 'InternalServer' then the Accounting field will invisible.
			But by default Accounting field is 'Disabled.' , so we escape this step.
		'''
		self._delete_network_auth_server()
		self.take_s1_snapshot()
		basic_info = self.NetworkPage.create_new_network()
		virtual_lan = basic_info.voice_network_dmo_channel_dynamic_optimization_radio_airtime('Voice',self.config.config_vars.edit_besteffort)
		security = virtual_lan.use_vlan_defaults()
		security.set_security_key_management('WPA-2 Personal')
		security.enable_mac_authentication()
		security.create_external_radius_server_in_auth_server_one()
		security.create_external_radius_server_in_auth_server_two()
		security.set_authentication_server_2_value(self.config.config_vars.edit_Authentication_server)
		access = security.click_on_next()
		access.finish_network_setup()
		edit_network = self.NetworkPage.edit_network()
		edit_network.edit_wpa_2_personal_voice_network_with_airtime_dmo_channel_value()
		self.LeftPanel.assert_delta_config_icon()
		edit_network = self.NetworkPage.edit_network()
		edit_network.assert_wpa_2_personal_voice_network_with_airtime_dmo_channel_value()
		self.LeftPanel.go_to_network_page()
		self.take_s2_snapshot()
		self._delete_network_auth_server()
		self.take_s3_snapshot()
		self.assert_s1_s2_diff(0)
		self.assert_s1_s3_diff()
		self.clear()
		
	def test_ath_9419_edit_personal_both_wpa_2_and_wpa_personal_voice_network_with_video_wmm_share_key(self):
		self._delete_network_auth_server()
		self.take_s1_snapshot()
		basic_info = self.NetworkPage.create_new_network()
		virtual_lan = basic_info.voice_network_with_advanced_settings_video_wmm_share()
		security = virtual_lan.use_vlan_defaults()
		access = security.set_both_wpa_2_wpa_64passphrase_format()
		access.finish_network_setup()
		edit_network = self.NetworkPage.edit_network()
		edit_network.edit_personal_both_wpa_2_and_wpa_personal_voice_network()
		self.LeftPanel.assert_delta_config_icon()
		edit_network = self.NetworkPage.edit_network()
		edit_network.assert_personal_both_wpa_2_and_wpa_personal_voice_network()
		self.LeftPanel.go_to_network_page()
		self.take_s2_snapshot()
		self._delete_network_auth_server()
		self.take_s3_snapshot()
		self.assert_s1_s2_diff(0)
		self.assert_s1_s3_diff()
		self.clear()
		
	def test_ath_12035_edit_personal_wpa_personal_voice_network_with_best_effort_wmm_share_static(self):
		self._delete_external_radius_servers()
		conf = self.config.config_vars
		self.take_s1_snapshot()
		basic_info = self.NetworkPage.create_new_network()
		vlan_obj = basic_info.voice_network_info()
		security = vlan_obj.use_vlan_defaults()
		access = security.set_key_management_wpa_personal()
		access.finish_network_setup()
		self.NetworkPage.assert_new_network()
		edit_network_page = self.NetworkPage.edit_network()
		edit_network_page.click_advanced_settings_accordion()
		edit_network_page.set_besteffort_wmm_share()
		edit_network_page.click_vlans_accordion()
		edit_network_page.set_static_vlan()
		edit_network_page.click_security_accordion()
		edit_network_page.enable_mac_authentication()
		edit_network_page.create_external_radiuds_server('1')
		edit_network_page.create_external_radiuds_server('2')
		edit_network_page._save_settings()
		edit_network_page = self.NetworkPage.edit_network()
		edit_network_page.click_advanced_settings_accordion()
		logger.debug('EditNetworkPage: Advanced Settings : Checking :is best effort wmm share set to 100')
		self.browser.assert_text(edit_network_page.besteffort_wmm_share, conf.edit_besteffort,'best effort wmm share is not set to 100','value')
		edit_network_page.click_security_accordion()
		edit_network_page.check_security_configurations_for_two_external_radius_servers()
		self.take_s2_snapshot()
		network_page = self.LeftPanel.go_to_network_page()
		self._delete_external_radius_servers()
		self.LeftPanel.assert_delta_config_icon()
		self.take_s3_snapshot()
		self.assert_s1_s2_diff(0)
		self.assert_s1_s3_diff()
		self.clear()

	def test_ath_12036_edit_personal_wpa_personal_voice_network_with_best_effort_wmm_share_default(self):
		self._delete_external_radius_servers()
		self.take_s1_snapshot()
		basic_info = self.NetworkPage.create_new_network()
		vlan_obj = basic_info.voice_network_with_advanced_settings_besteffort_wmm_share()
		security = vlan_obj.use_vlan_defaults()
		access = security.set_security_key_management('WPA Personal')
		security.enable_mac_authentication()
		security.create_external_radiuds_server('1')
		access = security.click_on_next()
		access.finish_network_setup()
		self.NetworkPage.assert_new_network()
		edit_network_page = self.NetworkPage.edit_network()
		edit_network_page.click_advanced_settings_accordion()
		edit_network_page.set_besteffort_wmm_share_default()
		edit_network_page.click_vlans_accordion()
		edit_network_page.click_security_accordion()
		edit_network_page.select_internalserver()
		edit_network_page.checking_for_authentication_server2_visibility()
		edit_network_page._save_settings()
		self.LeftPanel.assert_delta_config_icon()
		edit_network_page = self.NetworkPage.edit_network()
		edit_network_page.click_advanced_settings_accordion()
		self.browser.assert_text(edit_network_page.besteffort_wmm_share,self.config.config_vars.edit_besteffort_default,'Besteffort WMM Share not set to "0"','value')
		edit_network_page.click_security_accordion()
		edit_network_page.checking_for_authentication_server()
		edit_network_page.checking_for_authentication_server2_visibility()
		self.take_s2_snapshot()
		network_page = self.LeftPanel.go_to_network_page()
		self._delete_external_radius_servers()
		self.take_s3_snapshot()
		self.assert_s1_s2_diff(0)
		self.assert_s1_s3_diff()
		self.clear()
		
	def test_ath_12037_create_personal_wpa_2_personal_voice_network_with_video_wmm_share(self):
		conf = self.config.config_vars
		self.NetworkPage.delete_network_if_present()
		self.take_s1_snapshot()
		basic_info = self.NetworkPage.create_new_network()
		vlan_obj = basic_info.voice_network_with_advanced_settings_video_wmm_share()
		vlan_obj.edit_default_vlan_id(conf.vlan_id_300,next = False)
		vlan_obj.new.click()
		vlan_obj.set_rule_operator_value()
		vlan_obj.set_rule_string_value(conf.vlan_id_alpha)
		vlan_obj.set_rule_vlan_textbox_value(conf.vlan_id_200)
		vlan_obj._click_ok()
		security = vlan_obj.click_on_next()
		access = security.set_both_wpa_2_wpa_passphrase_format_64_hexadecimal_chars()
		access.finish_network_setup()
		self.LeftPanel.assert_delta_config_icon()
		edit_network_page = self.NetworkPage.edit_network()
		edit_network_page.assert_created_personal_wpa_2_personal_voice_network_with_video_wmm_share()
		self.take_s2_snapshot()
		network_page = self.LeftPanel.go_to_network_page()
		self.NetworkPage.assert_new_network()
		self.NetworkPage.delete_network_if_present()
		self.take_s3_snapshot()
		self.assert_s1_s2_diff(0)
		self.assert_s1_s3_diff()
		
	def test_ath_12038_edit_personal_both_wpa_2_and_wpa_personal_voice_network_with_video_wmm_share_key(self):
		self._delete_network_auth_server()
		self.take_s1_snapshot()
		basic_info = self.NetworkPage.create_new_network()
		virtual_lan = basic_info.voice_network_with_advanced_settings_video_wmm_share()
		security = virtual_lan.use_vlan_defaults()
		access = security.set_both_wpa_2_wpa_64passphrase_format()
		access.finish_network_setup()
		edit_network = self.NetworkPage.edit_network()
		edit_network.edit_personal_both_wpa_2_and_wpa_personal_voice_network()
		self.LeftPanel.assert_delta_config_icon()
		edit_network = self.NetworkPage.edit_network()
		edit_network.assert_personal_both_wpa_2_and_wpa_personal_voice_network()
		self.LeftPanel.go_to_network_page()
		self.take_s2_snapshot()
		self._delete_network_auth_server()
		self.take_s3_snapshot()
		self.assert_s1_s2_diff(0)
		self.assert_s1_s3_diff()
		self.clear()
		
	def test_ath_12039_create_personal_static_wep_voice_network_with_voice_wmm_share_key_management(self):
		self.NetworkPage.delete_network_if_present()
		self.take_s1_snapshot()
		basic_info = self.NetworkPage.create_new_network()
		vlan_obj = basic_info.voice_network_with_advanced_settings_voice_wmm_share()
		security = vlan_obj.use_vlan_defaults()
		security.set_static_wep_Tx_key()
		access = security.click_on_next()
		access.finish_network_setup()
		self.NetworkPage.assert_new_network()
		edit_network_page = self.NetworkPage.edit_network()
		edit_network_page.click_security_accordion()
		edit_network_page.check_static_wep_Tx_key()
		self.take_s2_snapshot()
		network_page = self.LeftPanel.go_to_network_page()
		self.NetworkPage.assert_new_network()
		self.NetworkPage.delete_network_if_present()
		self.LeftPanel.assert_delta_config_icon()
		self.take_s3_snapshot()
		self.assert_s1_s2_diff(0)
		self.assert_s1_s3_diff()
		self.clear()
		
	def test_ath_12040_edit_personal_static_wep_voice_network_with_voice_wmm_share(self):
		self._delete_external_radius_servers()
		self.take_s1_snapshot()
		basic_info = self.NetworkPage.create_new_network()
		vlan_obj = basic_info.voice_network_with_advanced_settings_voice_wmm_share()
		security = vlan_obj.use_vlan_defaults()
		security.enable_mac_authentication()
		security.create_external_radiuds_server('1')
		security.set_static_wep_Tx_key()
		access = security.click_on_next()
		access.finish_network_setup()
		self.NetworkPage.assert_new_network()
		edit_network_page = self.NetworkPage.edit_network()
		edit_network_page.click_advanced_settings_accordion()
		edit_network_page.edit_voice_wmm_share_default()
		edit_network_page.click_security_accordion()
		edit_network_page.edit_static_wep_network()
		self.NetworkPage.assert_new_network()
		edit_network_page = self.NetworkPage.edit_network()
		edit_network_page.click_security_accordion()
		edit_network_page.check_static_network_changes()
		self.take_s2_snapshot()
		network_page = self.LeftPanel.go_to_network_page()
		self.NetworkPage.assert_new_network()
		self.NetworkPage.delete_network_if_present()
		self._delete_external_radius_servers()
		self.LeftPanel.assert_delta_config_icon()
		self.take_s3_snapshot()
		self.assert_s1_s2_diff(0)
		self.assert_s1_s3_diff()
		self.clear()
		
	def test_ath_12041_edit_personal_static_wep_voice_network_with_content_filtering_blacklisting_mac_authentication(self):
		self.NetworkPage.delete_network_if_present()
		self.take_s1_snapshot()
		basic_info = self.NetworkPage.create_new_network()
		vlan_obj = basic_info.voice_network_info()
		security = vlan_obj.use_vlan_defaults()
		security.set_static_wep_Tx_key()
		security.configure_auth_server_settings(blacklisting=True)
		security.create_external_radius_server_in_auth_server_one()
		security.set_reauth_interval()
		access = security.click_on_next()
		access.finish_network_setup()
		edit_network = self.NetworkPage.edit_network()
		edit_network.edit_personal_static_wep_voice_network_with_content_filtering_blacklisting()
		self.LeftPanel.assert_delta_config_icon()
		edit_network = self.NetworkPage.edit_network()
		edit_network.assert_personal_static_wep_voice_network_with_content_filtering_blacklisting()
		self.LeftPanel.go_to_network_page()
		self.take_s2_snapshot()
		self._delete_network_auth_server()
		self.take_s3_snapshot()
		self.assert_s1_s2_diff(0)
		self.assert_s1_s3_diff()
		self.clear()
		
	def test_ath_12042_create_personal_wpa_2_personal_voice_network_with_content_filtering_key(self):
		self.NetworkPage.delete_network_if_present()
		self.take_s1_snapshot()
		basic_info = self.NetworkPage.create_new_network()
		vlan_obj = basic_info.voice_network_with_advanced_settings_enable_content_filtering()
		security = vlan_obj.use_vlan_defaults()
		access = security.enable_80211r_roaming()
		access.finish_network_setup()
		self.NetworkPage.assert_new_network()
		edit_network_page = self.NetworkPage.edit_network()
		edit_network_page.click_security_accordion()
		edit_network_page.check_security_configurations()
		self.take_s2_snapshot()
		network_page = self.LeftPanel.go_to_network_page()
		self.NetworkPage.assert_new_network()
		self.NetworkPage.delete_network_if_present()
		self.LeftPanel.assert_delta_config_icon()
		self.take_s3_snapshot()
		self.assert_s1_s2_diff(0)
		self.assert_s1_s3_diff()
		
	def test_ath_12043_edit_personal_wpa_personal_voice_network_with_content_filtering_key_management(self):
		self.take_s1_snapshot()
		conf = self.config.config_vars
		self._delete_network_auth_server()
		basic_info = self.NetworkPage.create_new_network()		
		virtual_lan = basic_info.voice_network_with_advanced_settings_enable_content_filtering()
		security = virtual_lan.use_vlan_defaults()
		access = security.configure_employee_security()
		access.finish_network_setup()
		edit_network_page = self.NetworkPage.edit_network()
		edit_network_page.click_advanced_settings_accordion()
		edit_network_page.content_filtering_dropdown.set(conf.content_filtering_disabled)
		edit_network_page.change_key_management()
		self.LeftPanel.assert_delta_config_icon()
		edit_network_page = self.NetworkPage.edit_network()
		edit_network_page.click_advanced_settings_accordion()
		self.browser.assert_drop_down_value(edit_network_page.content_filtering_dropdown, conf.content_filtering_disabled, "Content Filtering is not set 'Enabled'")
		edit_network_page.security_accordion.click()
		self.browser.assert_drop_down_value(edit_network_page.security_key_management, conf.key_management_value, "Key management is not set to 'WPA personal'")
		self.LeftPanel.go_to_network_page()
		self.take_s2_snapshot()
		self._delete_network_auth_server()
		self.take_s3_snapshot()
		self.assert_s1_s2_diff(0)
		self.assert_s1_s3_diff()
		self.clear()
		
	def test_ath_12044_edit_personal_both_wpa2_and_wpa_personal_voice_network_with_band_key_management_mac_authentication(self):
		self.take_s1_snapshot()
		conf = self.config.config_vars
		self._delete_network_auth_server()
		basic_info = self.NetworkPage.create_new_network()
		basic_info.voice_network_info_with_advanced_settings()
		virtual_lan = basic_info.click_on_next()	
		security = virtual_lan.use_vlan_defaults()
		access = security.set_key_management_wpa_personal() 
		access.finish_network_setup()
		edit_network_page = self.NetworkPage.edit_network()
		edit_network_page.change_advanced_band_settings()
		edit_network_page = self.NetworkPage.edit_network()
		edit_network_page.change_key_management_to_both_wpa2_wpa_personal()
		self.LeftPanel.assert_delta_config_icon()
		edit_network_page = self.NetworkPage.edit_network()
		edit_network_page.click_advanced_settings_accordion()
		self.browser.assert_drop_down_value(edit_network_page.band, conf.band_value, "Band is not set to 2.4 GHz")
		edit_network_page.security_accordion.click()
		self.browser.assert_drop_down_value(edit_network_page.security_key_management, conf.new_key_management_value, "Key management is not set to 'Both WPA & WPA2 personal'")
		self.browser.assert_drop_down_value(edit_network_page.mac_authentication, conf.mac_authentication_value, "MAC authentication is not set to 'Enabled'")
		self.LeftPanel.go_to_network_page()
		self.take_s2_snapshot()
		self._delete_network_auth_server()
		self.take_s3_snapshot()
		self.assert_s1_s2_diff(0)
		self.assert_s1_s3_diff()
		self.clear()		
		
	def test_ath_12045_edit_personal_static_wep_voice_network_with_band_key_management_wep_key_802_11_r_roaming(self):
		self.take_s1_snapshot()
		conf = self.config.config_vars
		self._delete_network_auth_server()
		basic_info = self.NetworkPage.create_new_network()
		basic_info.voice_network_info_with_advanced_settings()
		basic_info.set_24ghz_band()
		virtual_lan = basic_info.click_on_next()	
		security = virtual_lan.use_vlan_defaults()
		security.set_open_roaming_nondefault()
		access = security.configure_employee_security(True)
		access.finish_network_setup()
		edit_network_page = self.NetworkPage.edit_network()
		edit_network_page.change_advanced_band_settings_5_ghz()
		edit_network_page.security_accordion.click()
		edit_network_page.security_key_management.set(self.config.config_vars.static_wep_value)
		edit_network_page.wep_key.set(self.config.config_vars.wep_key)
		edit_network_page.wep_key_retype.set(self.config.config_vars.wep_key)
		edit_network_page.save_settings.click()
		self.LeftPanel.assert_delta_config_icon()
		edit_network_page = self.NetworkPage.edit_network()
		edit_network_page.click_advanced_settings_accordion()
		self.browser.assert_drop_down_value(edit_network_page.band, conf.band_value_5ghz, "Band is not set to 5 GHz")
		edit_network_page.security_accordion.click()
		self.browser.assert_drop_down_value(edit_network_page.security_key_management, conf.static_wep_value, "Key management is not set to 'Static WEP'")
		self.LeftPanel.go_to_network_page()
		self.take_s2_snapshot()
		self._delete_network_auth_server()
		self.take_s3_snapshot()
		self.assert_s1_s2_diff(0)
		self.assert_s1_s3_diff()
		self.clear()
		
	def test_ath_12046_edit_personal_wpa_2_personal_voice_network_with_band_key_management(self):
		self.NetworkPage.delete_network_if_present()
		self.take_s1_snapshot()
		basic_info = self.NetworkPage.create_new_network()
		vlan_obj = basic_info.voice_network_with_advanced_settings_5ghz_band()
		security = vlan_obj.use_vlan_defaults()
		security.set_security_level_and_key_management('Personal')
		access = security.click_on_next()
		access.finish_network_setup()
		self.NetworkPage.assert_new_network()
		edit_network_page = self.NetworkPage.edit_network()
		edit_network_page.click_advanced_settings_accordion()
		edit_network_page.set_band_default()
		edit_network_page.click_security_accordion()
		edit_network_page.edit_network_wpa_2_personal()
		edit_network_page.checking_for_wep_key_visibility()
		edit_network_page._save_settings()
		self.NetworkPage.assert_new_network()
		edit_network_page = self.NetworkPage.edit_network()
		edit_network_page.click_advanced_settings_accordion()
		edit_network_page.checking_for_band_all()
		edit_network_page.click_security_accordion()
		edit_network_page.checking_network_wpa_2_personal()
		self.take_s2_snapshot()
		network_page = self.LeftPanel.go_to_network_page()
		self.NetworkPage.assert_new_network()
		self.NetworkPage.delete_network_if_present()
		self.LeftPanel.assert_delta_config_icon()
		self.take_s3_snapshot()
		self.assert_s1_s2_diff(0)
		self.assert_s1_s3_diff()
		self.clear()